version: '{build}'

image: Visual Studio 2017
configuration: Release

before_build:
- dotnet restore

build:
  verbosity: minimal

artifacts:
- path: Failsafe\bin\$(configuration)\Failsafe*.nupkg
  name: Failsafe.nupkg

deploy:
- provider: NuGet
  api_key:
    secure: QuL5btMfw2HUtOrAO0C8hw0ILWLAY9Tq4Gp1uuDiPCjkOt7H8glITwlPCxoB/WWA
  artifact: Failsafe.nupkg
  on:
    branch: master
    appveyor_repo_tag: true